when:
  - event: tag
    ref: "refs/tags/v*"

depends_on:
  - check

labels:
  platform: linux/amd64

skip_clone: true

steps:
  - name: build
    image: bash
    commands:
      - git init
      - git remote add origin ${CI_REPO_CLONE_URL}
      - git fetch --no-tags --depth=1 origin ${CI_COMMIT_SHA}
      - git reset --hard ${CI_COMMIT_SHA}
      - rustup default stable
      - cargo build --release -p hpm-cli --bin hpm

  - name: test
    image: bash
    commands:
      - rustup default stable
      - cargo test --release --workspace

  - name: upload
    image: bash
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - bash ci/release-upload.sh target/release/hpm linux-x86_64
