when:
  - event: push
    branch: main

labels:
  platform: linux/amd64

skip_clone: true

steps:
  - name: mirror
    image: bash
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - git clone ${CI_REPO_CLONE_URL} /tmp/mirror
      - cd /tmp/mirror
      - git config user.email "ci@3db.dk"
      - git config user.name "Woodpecker CI"
      - git rm --cached -r .woodpecker/
      - git commit -m "Remove CI config for public mirror"
      - git remote add github https://x-access-token:${GITHUB_TOKEN}@github.com/3db-dk/hpm.git
      - git push github HEAD:main --force
      - git push github --tags
